# How to build:
# docker build --tag project:dev_${USER} -f Dockerfile_base . --build-arg USER_ID=$(id -u ${USER}) --build-arg GRUOP_ID=$(id -g ${USER})
# Reference :
# https://github.com/anibali/docker-pytorch/blob/master/dockerfiles/1.11.0-cuda11.5-ubuntu20.04/Dockerfile

# base image
FROM nvidia/cuda:11.5.1-base-ubuntu20.04

# maintainer
LABEL maintainer "chpark <bch0322@gmail.com>"

# args
ARG USER_ID
ARG GRUOP_ID

# set timezone
# TODO

# Remove any third-party apt sources to avoid issues with expiring keys.
RUN rm -f /etc/apt/sources.list.d/*.list

# Install some basic utilities
RUN apt-get update && apt-get -y --no-install-recommends install \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
 && rm -rf /var/lib/apt/lists/*

# Create a working directory
# RUN mkdir /opt    
WORKDIR /opt

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /opt
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER ${USR}

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN mkdir $HOME/.cache $HOME/.config \
 && chmod -R 777 $HOME

# Set up the Conda environment (using Miniforge)
ENV PATH=$HOME/mambaforge/bin:$PATH
COPY environment.yaml /opt/environment.yaml


# Set the default command to python3
CMD ["/bin/bash"]