SERVICE_NAME = core
COMMAND_BASE = /bin/bash
COMMAND_DEV = /bin/zsh

GID = $(shell id -g)
UID = $(shell id -u)
GRP = $(shell id -gn)
USR = $(shell id -un)

PROJECT_NAME = "${SERVICE_NAME}-${USR}"
IMAGE_NAME = "${USR}"

IMAGE_BASE_NAME = ${SERVICE_NAME}-base:latest
IMAGE_DEV_NAME = ${SERVICE_NAME}-dev:1.0.0
PROJECT_ROOT = /opt/${SERVICE_NAME}

CURRENT_PATH = $(shell pwd)
DOCKER_BUILD_CONTEXT_PATH = ./DockerFile

DOCKERFILE_BASE_NAME = Dockerfile_base
DOCKER_COMPOSE_BASE_NAME = Docker_compose_base.yaml

DOCKERFILE_DEV_NAME = Dockerfile_dev
DOCKER_COMPOSE_DEV_NAME = Docker_compose_dev.yaml

ENV_FILE_PATH = ${DOCKER_BUILD_CONTEXT_PATH}/.env

ENV_TEXT = "$\
GID=${GID}\n$\
UID=${UID}\n$\
GRP=${GRP}\n$\
USR=${USR}\n$\
IMAGE_NAME=${IMAGE_NAME}\n$\
PROJECT_ROOT=${PROJECT_ROOT}\n$\
CURRENT_PATH=${CURRENT_PATH}\n$\
DOCKER_BUILD_CONTEXT_PATH=${DOCKER_BUILD_CONTEXT_PATH}\n$\
DOCKERFILE_BASE_NAME=${DOCKERFILE_BASE_NAME}\n$\
DOCKER_COMPOSE_BASE_NAME=${DOCKER_COMPOSE_BASE_NAME}\n$\
DOCKERFILE_DEV_NAME=${DOCKERFILE_DEV_NAME}\n$\
DOCKER_COMPOSE_DEV_NAME=${DOCKER_COMPOSE_DEV_NAME}\n$\
"

${ENV_FILE_PATH}:
	printf ${ENV_TEXT} >> ${ENV_FILE_PATH}

env: ${ENV_FILE_PATH}

build-base:
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_BASE_NAME} -p ${PROJECT_NAME} up --build -d ${SERVICE_NAME}
up-base:
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_BASE_NAME} -p ${PROJECT_NAME} up -d ${SERVICE_NAME}
exec-base: 
	DOCKER_BUILDKIT=1 docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_BASE_NAME} -p ${PROJECT_NAME} exec ${SERVICE_NAME} ${COMMAND_BASE}
start-base:
	docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_BASE_NAME} -p ${PROJECT_NAME} start ${SERVICE_NAME}
down-base: 
	docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_BASE_NAME} -p ${PROJECT_NAME} down
run-base: 
	docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_BASE_NAME} -p ${PROJECT_NAME} run ${SERVICE_NAME} ${COMMAND_BASE}
ls-base: 
	docker compose ls -a

build-dev:
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_DEV_NAME} -p ${PROJECT_NAME} up --build -d ${SERVICE_NAME}
up-dev:
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_DEV_NAME} -p ${PROJECT_NAME} up -d ${SERVICE_NAME}
exec-dev: 
	DOCKER_BUILDKIT=1 docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_DEV_NAME} -p ${PROJECT_NAME} exec ${SERVICE_NAME} ${COMMAND_DEV}
start-dev:
	docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_DEV_NAME} -p ${PROJECT_NAME} start ${SERVICE_NAME}
down-dev: 
	docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_DEV_NAME} -p ${PROJECT_NAME} down
run-dev: 
	docker compose -f ${DOCKER_BUILD_CONTEXT_PATH}/${DOCKER_COMPOSE_DEV_NAME} -p ${PROJECT_NAME} run ${SERVICE_NAME} ${COMMAND_DEV}
ls-dev: 
	docker compose ls -a
