version: '3.0'  # YAML 파일 포맷 버전
services:
  core-base:
    image: ${IMAGE_NAME_BASE}
    build:
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_BASE}

  core-dev:
    hostname: core_dev
    image: ${IMAGE_NAME_DEV}
    ipc: host 
    tty: true
    stdin_open: true
    volumes:
      - ${CURRENT_PATH}:${PROJECT_ROOT} 
    working_dir: ${PROJECT_ROOT}
    build:
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_BASE}
      args: 
        IMAGE_NAME_BASE: ${IMAGE_NAME_BASE}
        PROJECT_ROOT: ${PROJECT_ROOT}
        GRP: ${GRP}
        USR: ${USR}
        GID: ${GID}
        UID: ${UID}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]