version: '3.0'  # YAML 파일 포맷 버전
services:
  core-base:
    image: ${IMAGE_NAME_BASE}
    build:
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_BASE}

  core-deploy:
    hostname: core-deploy
    image: ${IMAGE_NAME_DEPLOY}
    ipc: host 
    tty: true
    stdin_open: true
    volumes:
      - ${CURRENT_PATH}:${WORKDIR_PATH} 
    working_dir: ${WORKDIR_PATH}
    build:
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_DEPLOY}
      args: 
        BASE_IMAGE: ${IMAGE_NAME_BASE}
        WORKDIR_PATH: ${WORKDIR_PATH}
        GRP: ${GRP}
        USR: ${USR}
        GID: ${GID}
        UID: ${UID}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  core-dev:
    hostname: core-dev
    image: ${IMAGE_NAME_DEV}
    ipc: host 
    tty: true
    stdin_open: true
    volumes:
      - ${CURRENT_PATH}:${WORKDIR_PATH} 
    working_dir: ${WORKDIR_PATH}
    build:
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_DEV}
      args: 
        BASE_IMAGE: ${IMAGE_NAME_DEPLOY}
        WORKDIR_PATH: ${WORKDIR_PATH}
        GRP: ${GRP}
        USR: ${USR}
        GID: ${GID}
        UID: ${UID}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  core-research:
    hostname: core-research
    image: ${IMAGE_NAME_RESERACH}
    ipc: host 
    tty: true
    stdin_open: true
    volumes:
      - ${CURRENT_PATH}:${WORKDIR_PATH} 
    working_dir: ${WORKDIR_PATH}
    build:
      context: ${DOCKER_BUILD_CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_NAME_RESEARCH}
      args: 
        WORKDIR_PATH: ${WORKDIR_PATH}
        GRP: ${GRP}
        USR: ${USR}
        GID: ${GID}
        UID: ${UID}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]