# syntax=docker/dockerfile:1.4  # COPY --link 

# base image
ARG BASE_IMAGE
ARG USR
FROM ${BASE_IMAGE}

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /opt
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN mkdir $HOME/.cache $HOME/.config \
 && chmod -R 777 $HOME

# Install requirements
COPY requirements_dev.txt /requirements_dev.txt
RUN pip3 --no-cache-dir install -r /requirements_dev.txt

WORKDIR ${WORKDIR_PATH}
CMD ["/bin/bash"]