# syntax=docker/dockerfile:1.4  # COPY --link 

# base image
ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS train
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONIOENCODING=UTF-8

ENV TZ=Asia/Seoul
ARG DEBIAN_FRONTEND=noninteractive

# args
ARG GID
ARG UID
ARG USR
ARG GRP
ARG PASSWD=hello
ARG WORKDIR_PATH
ENV PYTHONPATH=${WORKDIR_PATH}

# Install requirements
COPY requirements_dev.txt /requirements_dev.txt
RUN apt-get update && apt-get -y --no-install-recommends install \
    zsh \ 
 && rm -rf /var/lib/apt/lists/*

RUN groupadd -f -g ${GID} ${GRP} && \
    useradd --shell /bin/zsh --create-home -u ${UID} -g ${GRP} \
        -p $(openssl passwd -1 ${PASSWD}) ${USR} && \
    echo "${USR} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

ENV HOME=/home/${USR}
RUN mkdir ${HOME}/.cache $HOME/.config \
 && chmod -R 777 $HOME

RUN pip3 install --upgrade pip
RUN pip3 --no-cache-dir install -r /requirements_dev.txt

# 터미널 설정 변경.
ARG ZSHRC_PATH=${HOME}/.zshrc
ARG ZSH_PURE_PATH=${HOME}/.zsh/pure
ARG ZSH_AUTO_PATH=${HOME}/.zsh/zsh-autosuggestions
ARG ZSH_HIGHLIGHT_PATH=${HOME}/.zsh/zsh-syntax-highlighting

# make dir
RUN mkdir ${WORKDIR_PATH}
RUN mkdir -p ${HOME}/.zsh

# oh-my-zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Pure
RUN git clone https://github.com/sindresorhus/pure.git ${ZSH_PURE_PATH}

# prompt
RUN {   echo "fpath+=${ZSH_PURE_PATH}"; \
        echo "typeset -A mycolors=(lightblue \"#9dd6f9\")"; \
        echo "zstyle :prompt:pure:path color \$mycolors[lightblue]"; \
        echo "zstyle ':prompt:pure:prompt:*' color magenta"; \
        echo "zstyle :prompt:pure:git:stash show yes"; \
        echo "autoload -Uz promptinit; promptinit"; \
        echo "prompt pure"; \
    } >> ${ZSHRC_PATH}

USER ${USR}
WORKDIR ${WORKDIR_PATH}
CMD ["/bin/zsh"]

