# syntax=docker/dockerfile:1.4  # COPY --link 

# base image
ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS train
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONIOENCODING=UTF-8

ENV TZ=Asia/Seoul
ARG DEBIAN_FRONTEND=noninteractive

# args
ARG GID
ARG UID
ARG USR
ARG GRP

ARG WORKDIR_PATH
ENV PYTHONPATH=${WORKDIR_PATH}

# Install requirements
COPY requirements_dev.txt /requirements_dev.txt
RUN apt-get update && apt-get -y --no-install-recommends install \
    zsh \ 
 && rm -rf /var/lib/apt/lists/*

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/zsh ${USR} \ 
    && chown -R ${USR}:${GRP} /opt
RUN echo "{USR} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER ${USR}

ENV HOME=/home/${USR}
RUN mkdir ${HOME}/.cache $HOME/.config \
 && chmod -R 777 $HOME

RUN pip3 install --upgrade pip
RUN pip3 --no-cache-dir install -r /requirements_dev.txt

# 터미널 설정 변경.
ARG ZSHRC_PATH=${HOME}/.zshrc
ARG PURE_PATH=${HOME}/.zsh/pure

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN mkdir ${WORKDIR_PATH}
RUN chmod -R 777 ${WORKDIR_PATH}

RUN mkdir -p ${HOME}/.zsh
RUN chmod -R 777 ${HOME}/.zsh

RUN git clone https://github.com/sindresorhus/pure.git ${PURE_PATH}
RUN {   echo "fpath+=${PURE_PATH}"; \
        echo "typeset -A mycolors=(lightblue \"#9dd6f9\")"; \
        echo "zstyle :prompt:pure:path color \$mycolors[lightblue]"; \
        echo "autoload -Uz promptinit; promptinit"; \
        echo "prompt pure"; \
    } >> ${ZSHRC_PATH}

WORKDIR ${WORKDIR_PATH}
CMD ["/bin/zsh"]

