# syntax=docker/dockerfile:1.4  # COPY --link 

########################################################################
ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS build-pure

# Z-shell 관련 패키지. 터미널 UI 및 UX 향상.
ARG PURE_URL=https://github.com/sindresorhus/pure.git
ARG ZSHA_URL=https://github.com/zsh-users/zsh-autosuggestions
ARG ZSHS_URL=https://github.com/zsh-users/zsh-syntax-highlighting.git

RUN git clone --depth 1 ${PURE_URL} /opt/zsh/pure
RUN git clone --depth 1 ${ZSHA_URL} /opt/zsh/zsh-autosuggestions
RUN git clone --depth 1 ${ZSHS_URL} /opt/zsh/zsh-syntax-highlighting

########################################################################

# base image
ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS train
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONIOENCODING=UTF-8

ENV TZ=Asia/Seoul
ARG DEBIAN_FRONTEND=noninteractive

# args
ARG GID
ARG UID
ARG USR
ARG GRP

ARG WORKDIR_PATH
ENV PYTHONPATH=${WORKDIR_PATH}

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash ${USR} \ 
    && chown -R ${USR}:${GRP} /opt
RUN echo "{USR} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER ${USR}


# All users can use /home/user as their home directory
ENV HOME=/home/${USR}
RUN mkdir $HOME/.cache $HOME/.config \
 && chmod -R 777 $HOME

# Install requirements
COPY requirements_dev.txt /requirements_dev.txt
RUN pip3 --no-cache-dir install -r /requirements_dev.txt

# 터미널 설정 변경.
RUN mkdir ${WORKDIR_PATH}
RUN chmod -R 777 ${WORKDIR_PATH}
ARG PURE_PATH=${WORKDIR_PATH}/.zsh/pure
ARG ZSH_FILE=${WORKDIR_PATH}/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
COPY --link --chown=${UID}:${GID} --from=build-pure /opt/zsh ${WORKDIR_PATH}/.zsh
RUN {   echo "fpath+=${PURE_PATH}"; \
        echo "autoload -Uz promptinit; promptinit"; \
        echo "prompt pure"; \
        echo "source ${ZSH_FILE}"; \
    } >> ${WORKDIR_PATH}/.zshrc

WORKDIR ${WORKDIR_PATH}
CMD ["/bin/bash"]
