# syntax=docker/dockerfile:1.4  # COPY --link 

# base image
FROM nvidia/cuda:11.6.1-base-ubuntu20.04

# # Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /opt
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER ${USR}

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN mkdir $HOME/.cache $HOME/.config \
 && chmod -R 777 $HOME

# Install requirements
COPY dockerFile/requirements_base.txt /requirements_base.txt
RUN pip3 --no-cache-dir install -r /requirements_base.txt

# 설치로 생성된 캐시 파일들을 삭제해서 용량 줄이기!
RUN apt-get clean && \
    apt-get autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/cache/* && \
    rm -rf /var/lib/log/*
    
WORKDIR ${PROJECT_ROOT}
CMD ["/bin/zsh"]
