# This workflow will test docker image build

name: Docker image build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'dockerfile/*'
      - 'makefile'
  
  pull_request:
    branches: [ "main" ]
    paths:
      - 'dockerfile/*'
      - 'makefile'
  
  workflow_dispatch:

jobs:
  build:
  
    runs-on: [self-hosted, mnist]

    steps:
    - uses: actions/checkout@v3
                
    - name: build docker dev image
      run: |
        rm -f dockerfile/.env
        make env
        make build-dev
        rm -f dockerfile/.env
    
    # - name: build docker research image
    #   run: |
    #     rm -f dockerfile/.env
    #     make env
    #     make build-research
    #     rm -f dockerfile/.env
